package com.example.demo.services;

import java.util.ArrayList;
import java.util.List;

import org.springframework.stereotype.Service;

import com.example.demo.models.Colonia;

@Service
public class ColoniaService {

    private List<Colonia> colonias;

    public ColoniaService() {
        this.colonias = new ArrayList<Colonia>();
        this.colonias.add(new Colonia(1, "12 de Diciembre"));
        this.colonias.add(new Colonia(2, "15 de Mayo (Tapias));"));
        this.colonias.add(new Colonia(3, "15 de Octubre"));
        this.colonias.add(new Colonia(4, "15 de Septiembre"));
        this.colonias.add(new Colonia(5, "16 de Septiembre"));
        this.colonias.add(new Colonia(6, "16 de Septiembre (Cieneguita de Fullman));"));
        this.colonias.add(new Colonia(7, "18 de Marzo"));
        this.colonias.add(new Colonia(8, "1° de Mayo"));
        this.colonias.add(new Colonia(9, "20 de Noviembre"));
        this.colonias.add(new Colonia(10, "20 de Noviembre"));
        this.colonias.add(new Colonia(11, "20 de Noviembre Fundo Legal"));
        this.colonias.add(new Colonia(12, "20 de Noviembre II"));
        this.colonias.add(new Colonia(13, "22 de Septiembre"));
        this.colonias.add(new Colonia(14, "23 de Marzo"));
        this.colonias.add(new Colonia(15, "27 de Noviembre"));
        this.colonias.add(new Colonia(16, "4 de Octubre y Delicias"));
        this.colonias.add(new Colonia(17, "5 de Febrero"));
        this.colonias.add(new Colonia(18, "5 de Mayo"));
        this.colonias.add(new Colonia(19, "8 de Septiembre"));
        this.colonias.add(new Colonia(20, "9 de Julio"));
        this.colonias.add(new Colonia(21, "Abraham González"));
        this.colonias.add(new Colonia(22, "Acereros"));
        this.colonias.add(new Colonia(23, "Acueducto"));
        this.colonias.add(new Colonia(24, "Adolfo López Mateos"));
        this.colonias.add(new Colonia(25, "Ágata"));
        this.colonias.add(new Colonia(26, "Alejandra"));
        this.colonias.add(new Colonia(27, "Alexa"));
        this.colonias.add(new Colonia(28, "Alianza por Durango"));
        this.colonias.add(new Colonia(29, "Amalia Solórzano"));
        this.colonias.add(new Colonia(30, "Ampliación 20 de Noviembre"));
        this.colonias.add(new Colonia(31, "Ampliación El Saltito"));
        this.colonias.add(new Colonia(32, "Ampliación Héctor Mayagoitia Domínguez"));
        this.colonias.add(new Colonia(33, "Ampliación Las Rosas"));
        this.colonias.add(new Colonia(34, "Ampliación Morelos Sur"));
        this.colonias.add(new Colonia(35, "Ampliación Nuevo Milenio"));
        this.colonias.add(new Colonia(36, "Ampliación Rosas del Tepeyac"));
        this.colonias.add(new Colonia(37, "Ampliación Tapias"));
        this.colonias.add(new Colonia(38, "Anahuac"));
        this.colonias.add(new Colonia(39, "Ángel Tejada Espino"));
        this.colonias.add(new Colonia(40, "Antigua Hacienda"));
        this.colonias.add(new Colonia(41, "Antonio Castillo"));
        this.colonias.add(new Colonia(42, "Antonio Gaxiola (La Carreta));"));
        this.colonias.add(new Colonia(43, "Antonio Ramirez"));
        this.colonias.add(new Colonia(44, "Aquiles Serdán"));
        this.colonias.add(new Colonia(45, "Aranjuez"));
        this.colonias.add(new Colonia(46, "Arantzazú"));
        this.colonias.add(new Colonia(47, "Arantzazu II"));
        this.colonias.add(new Colonia(48, "Aranza"));
        this.colonias.add(new Colonia(49, "Arco Iris"));
        this.colonias.add(new Colonia(50, "Armando del Castillo Franco"));
        this.colonias.add(new Colonia(51, "Arroyo Seco"));
        this.colonias.add(new Colonia(52, "Artemisas"));
        this.colonias.add(new Colonia(53, "Arturo Gamiz"));
        this.colonias.add(new Colonia(54, "Asentamientos Humanos"));
        this.colonias.add(new Colonia(55, "Aserradero"));
        this.colonias.add(new Colonia(56, "Atenas"));
        this.colonias.add(new Colonia(57, "Azcapotzalco"));
        this.colonias.add(new Colonia(58, "Azteca"));
        this.colonias.add(new Colonia(59, "Aztlán"));
        this.colonias.add(new Colonia(60, "Banderas del Águila"));
        this.colonias.add(new Colonia(61, "Barcelona"));
        this.colonias.add(new Colonia(62, "Barrio Tierra Blanca"));
        this.colonias.add(new Colonia(63, "Belisario Domínguez"));
        this.colonias.add(new Colonia(64, "Bellavista"));
        this.colonias.add(new Colonia(65, "Bello Amanecer"));
        this.colonias.add(new Colonia(66, "Bello Amanecer"));
        this.colonias.add(new Colonia(67, "Benigno Montoya"));
        this.colonias.add(new Colonia(68, "Benito Juárez"));
        this.colonias.add(new Colonia(69, "Benito Juárez"));
        this.colonias.add(new Colonia(70, "Benito Juárez"));
        this.colonias.add(new Colonia(71, "Benjamín Méndez"));
        this.colonias.add(new Colonia(72, "Bosques"));
        this.colonias.add(new Colonia(73, "Bosques del Nayar"));
        this.colonias.add(new Colonia(74, "Bosques del Valle"));
        this.colonias.add(new Colonia(75, "Brisas Diamante"));
        this.colonias.add(new Colonia(76, "Buena Vista"));
        this.colonias.add(new Colonia(77, "Buenos Aires"));
        this.colonias.add(new Colonia(78, "Burócrata"));
        this.colonias.add(new Colonia(79, "Calera"));
        this.colonias.add(new Colonia(80, "California"));
        this.colonias.add(new Colonia(81, "Camino Real"));
        this.colonias.add(new Colonia(82, "Caminos del Sol"));
        this.colonias.add(new Colonia(83, "Campestre de Durango"));
        this.colonias.add(new Colonia(84, "Campestre de Durango II"));
        this.colonias.add(new Colonia(85, "Campestre Jacarandas"));
        this.colonias.add(new Colonia(86, "Campestre las Granjas"));
        this.colonias.add(new Colonia(87, "Campestre Los Pinos"));
        this.colonias.add(new Colonia(88, "Campestre Martinica"));
        this.colonias.add(new Colonia(89, "Campo Alegre"));
        this.colonias.add(new Colonia(90, "Canelas"));
        this.colonias.add(new Colonia(91, "Cantarranas"));
        this.colonias.add(new Colonia(92, "Carlos Luna"));
        this.colonias.add(new Colonia(93, "Centauro del Norte"));
        this.colonias.add(new Colonia(94, "Centro SCT Durango"));
        this.colonias.add(new Colonia(95, "Cerrada las Torres"));
        this.colonias.add(new Colonia(96, "Cerro de Guadalupe"));
        this.colonias.add(new Colonia(97, "Cerro del Mercado"));
        this.colonias.add(new Colonia(98, "Cesar Guillermo Meraz"));
        this.colonias.add(new Colonia(99, "Chapultepec"));
        this.colonias.add(new Colonia(100, "Chulas Fronteras"));
        this.colonias.add(new Colonia(101, "Cibeles"));
        this.colonias.add(new Colonia(102, "Cielo Vista"));
        this.colonias.add(new Colonia(103, "Ciénega"));
        this.colonias.add(new Colonia(104, "Ciudad Industrial"));
        this.colonias.add(new Colonia(105, "Claveles 1 (Ampliación Luis Donaldo Colosio));"));
        this.colonias.add(new Colonia(106, "Claveles II"));
        this.colonias.add(new Colonia(107, "CNOP"));
        this.colonias.add(new Colonia(108, "Colinas del Saltito"));
        this.colonias.add(new Colonia(109, "Colinas de San Isidro"));
        this.colonias.add(new Colonia(110, "Comisión Federal de Electricidad"));
        this.colonias.add(new Colonia(111, "Constitución"));
        this.colonias.add(new Colonia(112, "Constituyentes"));
        this.colonias.add(new Colonia(113, "Contreras"));
        this.colonias.add(new Colonia(114, "Cortijo Residencial"));
        this.colonias.add(new Colonia(115, "Cristóbal Colón"));
        this.colonias.add(new Colonia(116, "Cristóbal Colón"));
        this.colonias.add(new Colonia(117, "Cuadra del Ferrocarril"));
        this.colonias.add(new Colonia(118, "Cumbres Residencial"));
        this.colonias.add(new Colonia(119, "De Analco"));
        this.colonias.add(new Colonia(120, "Del Bosque"));
        this.colonias.add(new Colonia(121, "Del Lago"));
        this.colonias.add(new Colonia(122, "Del Maestro"));
        this.colonias.add(new Colonia(123, "Del Valle"));
        this.colonias.add(new Colonia(124, "Democracia Sindical"));
        this.colonias.add(new Colonia(125, "Diana Laura R de Colosio"));
        this.colonias.add(new Colonia(126, "División del Norte"));
        this.colonias.add(new Colonia(127, "Dolores del Río"));
        this.colonias.add(new Colonia(128, "Dolores Hidalgo"));
        this.colonias.add(new Colonia(129, "Domingo Arrieta"));
        this.colonias.add(new Colonia(130, "Durango Nuevo 1"));
        this.colonias.add(new Colonia(131, "Durango Nuevo II"));
        this.colonias.add(new Colonia(132, "Durango (Pdte. Guadalupe Victoria));"));
        this.colonias.add(new Colonia(133, "Edmundo Ravelo Duarte"));
        this.colonias.add(new Colonia(134, "Ejidal"));
        this.colonias.add(new Colonia(135, "Ejidal"));
        this.colonias.add(new Colonia(136, "El Arenal (San Jerónimo));"));
        this.colonias.add(new Colonia(137, "El Bosque"));
        this.colonias.add(new Colonia(138, "El Bosque Residencial"));
        this.colonias.add(new Colonia(139, "El Brillante"));
        this.colonias.add(new Colonia(140, "El Calvario"));
        this.colonias.add(new Colonia(141, "El Carmen"));
        this.colonias.add(new Colonia(142, "El Carmen y Anexas"));
        this.colonias.add(new Colonia(143, "El Ciprés"));
        this.colonias.add(new Colonia(144, "El Durazno"));
        this.colonias.add(new Colonia(145, "El Durazno 1"));
        this.colonias.add(new Colonia(146, "El Edén"));
        this.colonias.add(new Colonia(147, "El Encinal"));
        this.colonias.add(new Colonia(148, "El Ensueño"));
        this.colonias.add(new Colonia(149, "El Lucero"));
        this.colonias.add(new Colonia(150, "El Manzanal"));
        this.colonias.add(new Colonia(151, "El Milagro"));
        this.colonias.add(new Colonia(152, "El Mirador"));
        this.colonias.add(new Colonia(153, "El Naranjal"));
        this.colonias.add(new Colonia(154, "El Nayar"));
        this.colonias.add(new Colonia(155, "El Pueblito"));
        this.colonias.add(new Colonia(156, "El Refugio"));
        this.colonias.add(new Colonia(157, "El Refugio (El Conejo));"));
        this.colonias.add(new Colonia(158, "El Renacimiento"));
        this.colonias.add(new Colonia(159, "El Rosario"));
        this.colonias.add(new Colonia(160, "El Saltito"));
        this.colonias.add(new Colonia(161, "El Saltito 1"));
        this.colonias.add(new Colonia(162, "El Soldado"));
        this.colonias.add(new Colonia(163, "El Soliceño"));
        this.colonias.add(new Colonia(164, "El Tepetate"));
        this.colonias.add(new Colonia(165, "El Toboso"));
        this.colonias.add(new Colonia(166, "El Tunal"));
        this.colonias.add(new Colonia(167, "Emiliano Zapata"));
        this.colonias.add(new Colonia(168, "Empalme Purísima"));
        this.colonias.add(new Colonia(169, "Empleado Municipal"));
        this.colonias.add(new Colonia(170, "España"));
        this.colonias.add(new Colonia(171, "Español"));
        this.colonias.add(new Colonia(172, "Esperanza"));
        this.colonias.add(new Colonia(173, "Fátima"));
        this.colonias.add(new Colonia(174, "Felipe Ángeles"));
        this.colonias.add(new Colonia(175, "Fideicomiso Ciudad Industrial"));
        this.colonias.add(new Colonia(176, "Fidel Velázquez I"));
        this.colonias.add(new Colonia(177, "Fidel Velázquez II"));
        this.colonias.add(new Colonia(178, "Finca el Tlalpeño"));
        this.colonias.add(new Colonia(179, "Finca las Flores"));
        this.colonias.add(new Colonia(180, "Florencia"));
        this.colonias.add(new Colonia(181, "F.O.S. La Virgen"));
        this.colonias.add(new Colonia(182, "Fraccionamiento Campestre las Granjas Dos"));
        this.colonias.add(new Colonia(183, "Fraccionamiento Campestre las Granjas Uno"));
        this.colonias.add(new Colonia(184, "Fraccionamiento Campestre Residencial Navíos"));
        this.colonias.add(new Colonia(185, "Fraccionamiento el Soldado"));
        this.colonias.add(new Colonia(186, "Fraccionamiento las Quebradas"));
        this.colonias.add(new Colonia(187, "Fraccionamiento Paraíso de La Sierra"));
        this.colonias.add(new Colonia(188, "Fraccionamiento San Miguel de Casa Blanca"));
        this.colonias.add(new Colonia(189, "Francisco González de La Vega"));
        this.colonias.add(new Colonia(190, "Francisco I Madero"));
        this.colonias.add(new Colonia(191, "Francisco Sarabia"));
        this.colonias.add(new Colonia(192, "Francisco Villa"));
        this.colonias.add(new Colonia(193, "Francisco Villa Nuevo"));
        this.colonias.add(new Colonia(194, "Francisco Villa Viejo"));
        this.colonias.add(new Colonia(195, "Francisco Zarco"));
        this.colonias.add(new Colonia(196, "Fray Diego de La Cadena"));
        this.colonias.add(new Colonia(197, "Fray Francisco Montes de Oca"));
        this.colonias.add(new Colonia(198, "FSTSE"));
        this.colonias.add(new Colonia(199, "Gabino Santillán"));
        this.colonias.add(new Colonia(200, "Gardenias Privadas Residencial"));
        this.colonias.add(new Colonia(201, "Gaviotas II"));
        this.colonias.add(new Colonia(202, "Genaro Vázquez"));
        this.colonias.add(new Colonia(203, "General Carlos Real"));
        this.colonias.add(new Colonia(204, "General Felipe Ángeles"));
        this.colonias.add(new Colonia(205, "General Lázaro Cárdenas"));
        this.colonias.add(new Colonia(206, "General Mariano Matamoros"));
        this.colonias.add(new Colonia(207, "General Máximo García"));
        this.colonias.add(new Colonia(208, "Geraldine"));
        this.colonias.add(new Colonia(209, "Girasoles"));
        this.colonias.add(new Colonia(210, "Girasoles"));
        this.colonias.add(new Colonia(211, "Gobernadores"));
        this.colonias.add(new Colonia(212, "Granja Alejandrina"));
        this.colonias.add(new Colonia(213, "Granja Betania"));
        this.colonias.add(new Colonia(214, "Granja Cristy"));
        this.colonias.add(new Colonia(215, "Granja Delicias"));
        this.colonias.add(new Colonia(216, "Granja Don Luis Sandoval"));
        this.colonias.add(new Colonia(217, "Granja Dos Arbolitos"));
        this.colonias.add(new Colonia(218, "Granja Edy (Las Artemisas));"));
        this.colonias.add(new Colonia(219, "Granja el Bajío"));
        this.colonias.add(new Colonia(220, "Granja el Peligro"));
        this.colonias.add(new Colonia(221, "Granja el Refugio"));
        this.colonias.add(new Colonia(222, "Granja el Rosario"));
        this.colonias.add(new Colonia(223, "Granja el Shaddai"));
        this.colonias.add(new Colonia(224, "Granja Espeleta"));
        this.colonias.add(new Colonia(225, "Granja Familia Martínez"));
        this.colonias.add(new Colonia(226, "Granja Graciela"));
        this.colonias.add(new Colonia(227, "Granja Guadalupe (Granja Natera));"));
        this.colonias.add(new Colonia(228, "Granja Jovana"));
        this.colonias.add(new Colonia(229, "Granja la Casita"));
        this.colonias.add(new Colonia(230, "Granja la Maroma"));
        this.colonias.add(new Colonia(231, "Granja las Gabrielas"));
        this.colonias.add(new Colonia(232, "Granja Laura"));
        this.colonias.add(new Colonia(233, "Granja Loma Bonita"));
        this.colonias.add(new Colonia(234, "Granja los Arcos"));
        this.colonias.add(new Colonia(235, "Granja los Riegos"));
        this.colonias.add(new Colonia(236, "Granja María Luisa"));
        this.colonias.add(new Colonia(237, "Granja Martínez"));
        this.colonias.add(new Colonia(238, "Granja Mis Ilusiones"));
        this.colonias.add(new Colonia(239, "Granja San Andrés"));
        this.colonias.add(new Colonia(240, "Granja Santa Clara"));
        this.colonias.add(new Colonia(241, "Granja Santa Fe"));
        this.colonias.add(new Colonia(242, "Granja Santa Lourdes"));
        this.colonias.add(new Colonia(243, "Granja Santa Rita"));
        this.colonias.add(new Colonia(244, "Granja Santa Teresa"));
        this.colonias.add(new Colonia(245, "Granjas del Río"));
        this.colonias.add(new Colonia(246, "Granja Tres Potrillos"));
        this.colonias.add(new Colonia(247, "Guadalupe"));
        this.colonias.add(new Colonia(248, "Guadalupe"));
        this.colonias.add(new Colonia(249, "Guadalupe Victoria INFONAVIT"));
        this.colonias.add(new Colonia(250, "Guadiana"));
        this.colonias.add(new Colonia(251, "Guillermina"));
        this.colonias.add(new Colonia(252, "Gustavo Díaz Ordaz"));
        this.colonias.add(new Colonia(253, "Hacienda de Fray Diego"));
        this.colonias.add(new Colonia(254, "Hacienda de Otinapa"));
        this.colonias.add(new Colonia(255, "Hacienda de Tapias"));
        this.colonias.add(new Colonia(256, "Hacienda el Chorro"));
        this.colonias.add(new Colonia(257, "Hacienda la Pila"));
        this.colonias.add(new Colonia(258, "Hacienda las Flores"));
        this.colonias.add(new Colonia(259, "Hacienda Residencial San Fernanda"));
        this.colonias.add(new Colonia(260, "Haciendas"));
        this.colonias.add(new Colonia(261, "Hacienda San Lorenzo"));
        this.colonias.add(new Colonia(262, "Hacienda San Martina"));
        this.colonias.add(new Colonia(263, "Haciendas del Campestre"));
        this.colonias.add(new Colonia(264, "Haciendas del Pedregal I"));
        this.colonias.add(new Colonia(265, "Haciendas del Pedregal II"));
        this.colonias.add(new Colonia(266, "Haciendas el Saltito"));
        this.colonias.add(new Colonia(267, "Heberto Castillo"));
        this.colonias.add(new Colonia(268, "Héctor Mayagoitia Domínguez"));
        this.colonias.add(new Colonia(269, "Hernandez"));
        this.colonias.add(new Colonia(270, "Héroe de Nacozari"));
        this.colonias.add(new Colonia(271, "Herrera Leyva"));
        this.colonias.add(new Colonia(272, "Hidalgo"));
        this.colonias.add(new Colonia(273, "Hipódromo"));
        this.colonias.add(new Colonia(274, "Hogares del Parque"));
        this.colonias.add(new Colonia(275, "Huizache I"));
        this.colonias.add(new Colonia(276, "Huizache II"));
        this.colonias.add(new Colonia(277, "Ignacio López Rayón"));
        this.colonias.add(new Colonia(278, "Ignacio Zaragoza"));
        this.colonias.add(new Colonia(279, "Ignacio Zaragoza"));
        this.colonias.add(new Colonia(280, "IMSS"));
        this.colonias.add(new Colonia(281, "Independencia y Libertad"));
        this.colonias.add(new Colonia(282, "Industrial Korian"));
        this.colonias.add(new Colonia(283, "Industrial Ladrillera"));
        this.colonias.add(new Colonia(284, "Industrial Nuevo Durango"));
        this.colonias.add(new Colonia(285, "INFONAVIT"));
        this.colonias.add(new Colonia(286, "Insurgentes"));
        this.colonias.add(new Colonia(287, "Isabel Almanza"));
        this.colonias.add(new Colonia(288, "ISSSTE"));
        this.colonias.add(new Colonia(289, "IV Centenario"));
        this.colonias.add(new Colonia(290, "Jalisco"));
        this.colonias.add(new Colonia(291, "Jardines de Cancún"));
        this.colonias.add(new Colonia(292, "Jardines de Durango"));
        this.colonias.add(new Colonia(293, "Jardines del Nayar"));
        this.colonias.add(new Colonia(294, "Jardines del Real I"));
        this.colonias.add(new Colonia(295, "Jardines del Real II"));
        this.colonias.add(new Colonia(296, "Jardines del Real III"));
        this.colonias.add(new Colonia(297, "Jardines del Real IV"));
        this.colonias.add(new Colonia(298, "Jardines de San Antonio I"));
        this.colonias.add(new Colonia(299, "Jesús María"));
        this.colonias.add(new Colonia(300, "J Guadalupe Rodriguez"));
        this.colonias.add(new Colonia(301, "José Ángel Leal"));
        this.colonias.add(new Colonia(302, "José López Portillo"));
        this.colonias.add(new Colonia(303, "José María Morelos y Pavón (La Tinaja));"));
        this.colonias.add(new Colonia(304, "José María Pino Suárez"));
        this.colonias.add(new Colonia(305, "José Martí"));
        this.colonias.add(new Colonia(306, "José Refugio Salcido"));
        this.colonias.add(new Colonia(307, "José Revueltas"));
        this.colonias.add(new Colonia(308, "Joyas del Valle"));
        this.colonias.add(new Colonia(309, "Juan Aldama"));
        this.colonias.add(new Colonia(310, "Juan B Ceballos"));
        this.colonias.add(new Colonia(311, "Juan de La Barrera"));
        this.colonias.add(new Colonia(312, "Juan Escutia"));
        this.colonias.add(new Colonia(313, "Juan Lira Bracho"));
        this.colonias.add(new Colonia(314, "Justicia Social"));
        this.colonias.add(new Colonia(315, "La Arboleda"));
        this.colonias.add(new Colonia(316, "La Boca del Mezquital"));
        this.colonias.add(new Colonia(317, "Labor de Guadalupe"));
        this.colonias.add(new Colonia(318, "La Cima"));
        this.colonias.add(new Colonia(319, "La Cruz (Sayula));"));
        this.colonias.add(new Colonia(320, "Ladera del Pedregal"));
        this.colonias.add(new Colonia(321, "La Esmeralda"));
        this.colonias.add(new Colonia(322, "La Esmeralda"));
        this.colonias.add(new Colonia(323, "La Estrella"));
        this.colonias.add(new Colonia(324, "La Ferreria (Cuatro de Octubre));"));
        this.colonias.add(new Colonia(325, "La Forestal"));
        this.colonias.add(new Colonia(326, "La Glorieta"));
        this.colonias.add(new Colonia(327, "La Granja"));
        this.colonias.add(new Colonia(328, "Laguna Colorada"));
        this.colonias.add(new Colonia(329, "La Hacienda"));
        this.colonias.add(new Colonia(330, "La Huerta"));
        this.colonias.add(new Colonia(331, "La Joya"));
        this.colonias.add(new Colonia(332, "La Joya"));
        this.colonias.add(new Colonia(333, "La Loma"));
        this.colonias.add(new Colonia(334, "La Lomita"));
        this.colonias.add(new Colonia(335, "La Luz"));
        this.colonias.add(new Colonia(336, "La Luz"));
        this.colonias.add(new Colonia(337, "La Moderna"));
        this.colonias.add(new Colonia(338, "La Nogalera"));
        this.colonias.add(new Colonia(339, "La Noria"));
        this.colonias.add(new Colonia(340, "La Ponderosa"));
        this.colonias.add(new Colonia(341, "La Pradera"));
        this.colonias.add(new Colonia(342, "La Quinta"));
        this.colonias.add(new Colonia(343, "Las Águilas I"));
        this.colonias.add(new Colonia(344, "Las Águilas II"));
        this.colonias.add(new Colonia(345, "Las Alamedas"));
        this.colonias.add(new Colonia(346, "Las Alamedas II"));
        this.colonias.add(new Colonia(347, "Las Alamedas MT"));
        this.colonias.add(new Colonia(348, "Las Américas"));
        this.colonias.add(new Colonia(349, "Las Brisas"));
        this.colonias.add(new Colonia(350, "Las Bugambilias"));
        this.colonias.add(new Colonia(351, "Las Bugambilias"));
        this.colonias.add(new Colonia(352, "Las Calandrias"));
        this.colonias.add(new Colonia(353, "Las Calzadas"));
        this.colonias.add(new Colonia(354, "Las Cumbres"));
        this.colonias.add(new Colonia(355, "Las Cumbres"));
        this.colonias.add(new Colonia(356, "Las Encinas"));
        this.colonias.add(new Colonia(357, "Las Esperanzas"));
        this.colonias.add(new Colonia(358, "Las Flores"));
        this.colonias.add(new Colonia(359, "Las Flores Sur"));
        this.colonias.add(new Colonia(360, "Las Fuentes"));
        this.colonias.add(new Colonia(361, "Las Huertas"));
        this.colonias.add(new Colonia(362, "Las Magdalenas"));
        this.colonias.add(new Colonia(363, "Las Maravillas"));
        this.colonias.add(new Colonia(364, "Las Margaritas"));
        this.colonias.add(new Colonia(365, "Las Milpas"));
        this.colonias.add(new Colonia(366, "Las Misiones (Edificios de Departamentos));"));
        this.colonias.add(new Colonia(367, "Las Nubes I"));
        this.colonias.add(new Colonia(368, "Las Nubes II"));
        this.colonias.add(new Colonia(369, "Las Palmas"));
        this.colonias.add(new Colonia(370, "Las Playas"));
        this.colonias.add(new Colonia(371, "Las Privanzas"));
        this.colonias.add(new Colonia(372, "Las Quintas"));
        this.colonias.add(new Colonia(373, "Las Vegas"));
        this.colonias.add(new Colonia(374, "La Virgen"));
        this.colonias.add(new Colonia(375, "Lázaro Cárdenas"));
        this.colonias.add(new Colonia(376, "Liberación Social"));
        this.colonias.add(new Colonia(377, "Llano Grande"));
        this.colonias.add(new Colonia(378, "Loma Bonita I"));
        this.colonias.add(new Colonia(379, "Loma Bonita II"));
        this.colonias.add(new Colonia(380, "Loma Dorada"));
        this.colonias.add(new Colonia(381, "Loma Dorada Diamante"));
        this.colonias.add(new Colonia(382, "Lomas"));
        this.colonias.add(new Colonia(383, "Lomas del Guadiana"));
        this.colonias.add(new Colonia(384, "Lomas del Parque"));
        this.colonias.add(new Colonia(385, "Lomas del Sahuatoba"));
        this.colonias.add(new Colonia(386, "Lomas de San Isidro"));
        this.colonias.add(new Colonia(387, "Los Agaves"));
        this.colonias.add(new Colonia(388, "Los Alamitos"));
        this.colonias.add(new Colonia(389, "Los Álamos"));
        this.colonias.add(new Colonia(390, "Los Álamos"));
        this.colonias.add(new Colonia(391, "Los Altares"));
        this.colonias.add(new Colonia(392, "Los Ángeles"));
        this.colonias.add(new Colonia(393, "Los Ángeles Villas"));
        this.colonias.add(new Colonia(394, "Los Arbolitos I"));
        this.colonias.add(new Colonia(395, "Los Arbolitos II"));
        this.colonias.add(new Colonia(396, "Los Arbolitos III"));
        this.colonias.add(new Colonia(397, "Los Cedros Residencial"));
        this.colonias.add(new Colonia(398, "Los Duraznos"));
        this.colonias.add(new Colonia(399, "Los Encinos"));
        this.colonias.add(new Colonia(400, "Los Eucaliptos"));
        this.colonias.add(new Colonia(401, "Los Fresnos"));
        this.colonias.add(new Colonia(402, "Los Fuentes"));
        this.colonias.add(new Colonia(403, "Los Nogales"));
        this.colonias.add(new Colonia(404, "Los Pinos Residencial"));
        this.colonias.add(new Colonia(405, "Los Remedios"));
        this.colonias.add(new Colonia(406, "Los Sauces"));
        this.colonias.add(new Colonia(407, "Los Tulipanes I"));
        this.colonias.add(new Colonia(408, "Lucio Cabañas"));
        this.colonias.add(new Colonia(409, "Luis Donaldo Colosio"));
        this.colonias.add(new Colonia(410, "Luis Echeverría Alvarez"));
        this.colonias.add(new Colonia(411, "Luz del Carmen"));
        this.colonias.add(new Colonia(412, "Luz y Esperanza"));
        this.colonias.add(new Colonia(413, "Maderera"));
        this.colonias.add(new Colonia(414, "Madrazo"));
        this.colonias.add(new Colonia(415, "Málaga"));
        this.colonias.add(new Colonia(416, "Manuel Buendía"));
        this.colonias.add(new Colonia(417, "Manuel Gómez Morin"));
        this.colonias.add(new Colonia(418, "Margarita Maza de Juárez"));
        this.colonias.add(new Colonia(419, "María Luisa"));
        this.colonias.add(new Colonia(420, "Massie"));
        this.colonias.add(new Colonia(421, "Máximo Gamiz Fernández"));
        this.colonias.add(new Colonia(422, "Mesas de Urbina"));
        this.colonias.add(new Colonia(423, "Metates"));
        this.colonias.add(new Colonia(424, "México"));
        this.colonias.add(new Colonia(425, "Miguel de La Madrid Hurtado"));
        this.colonias.add(new Colonia(426, "Miguel González Avelar"));
        this.colonias.add(new Colonia(427, "Milenio 450"));
        this.colonias.add(new Colonia(428, "Minero Napoleón Gómez Sada"));
        this.colonias.add(new Colonia(429, "Minerva"));
        this.colonias.add(new Colonia(430, "Minerva (Colonia));"));
        this.colonias.add(new Colonia(431, "Mi Patria es Primero (Mesa del Cuervo));"));
        this.colonias.add(new Colonia(432, "Miramar"));
        this.colonias.add(new Colonia(433, "Mireles"));
        this.colonias.add(new Colonia(434, "Molinillos"));
        this.colonias.add(new Colonia(435, "Monte Bello"));
        this.colonias.add(new Colonia(436, "Morcillo"));
        this.colonias.add(new Colonia(437, "Morelos"));
        this.colonias.add(new Colonia(438, "Morelos Norte"));
        this.colonias.add(new Colonia(439, "Morelos Sur"));
        this.colonias.add(new Colonia(440, "Morga"));
        this.colonias.add(new Colonia(441, "Navacoyan"));
        this.colonias.add(new Colonia(442, "Navajas"));
        this.colonias.add(new Colonia(443, "Nazas"));
        this.colonias.add(new Colonia(444, "Nicolás Romero"));
        this.colonias.add(new Colonia(445, "Niños Héroes"));
        this.colonias.add(new Colonia(446, "Niños Héroes"));
        this.colonias.add(new Colonia(447, "Niños Héroes de Chapultepec"));
        this.colonias.add(new Colonia(448, "Nueva Patria (Santo Domingo));"));
        this.colonias.add(new Colonia(449, "Nueva Vizcaya"));
        this.colonias.add(new Colonia(450, "Nuevo Amanecer"));
        this.colonias.add(new Colonia(451, "Nuevo Durango I"));
        this.colonias.add(new Colonia(452, "Nuevo Durango II"));
        this.colonias.add(new Colonia(453, "Nuevo Durango III"));
        this.colonias.add(new Colonia(454, "Nuevo Pedregal"));
        this.colonias.add(new Colonia(455, "Nuevo Pedregal III"));
        this.colonias.add(new Colonia(456, "Nuevo Valle"));
        this.colonias.add(new Colonia(457, "Ocampo"));
        this.colonias.add(new Colonia(458, "Octavio Paz"));
        this.colonias.add(new Colonia(459, "Ojo de Agua del Cazador (Cruz de Piedra));"));
        this.colonias.add(new Colonia(460, "Olga Margarita"));
        this.colonias.add(new Colonia(461, "Otinapa"));
        this.colonias.add(new Colonia(462, "Palacio de Gobierno del Estado de Durango"));
        this.colonias.add(new Colonia(463, "Paloma"));
        this.colonias.add(new Colonia(464, "Paraíso"));
        this.colonias.add(new Colonia(465, "Parras de La Fuente"));
        this.colonias.add(new Colonia(466, "Paseo de las Mangas"));
        this.colonias.add(new Colonia(467, "Paseo del Saltito"));
        this.colonias.add(new Colonia(468, "Paso Real"));
        this.colonias.add(new Colonia(469, "Patria Libre"));
        this.colonias.add(new Colonia(470, "Pedregal de La Nueva España"));
        this.colonias.add(new Colonia(471, "Pedregal de San Pedro"));
        this.colonias.add(new Colonia(472, "Picachos"));
        this.colonias.add(new Colonia(473, "Pilar de Zaragoza"));
        this.colonias.add(new Colonia(474, "Plan de Ayala"));
        this.colonias.add(new Colonia(475, "Planta de Impregnación (Ferrocarrilera));"));
        this.colonias.add(new Colonia(476, "Poblado Ejido Benito Juárez"));
        this.colonias.add(new Colonia(477, "Porfirio Díaz"));
        this.colonias.add(new Colonia(478, "Potreros del Refugio"));
        this.colonias.add(new Colonia(479, "Praderas del Sur"));
        this.colonias.add(new Colonia(480, "Praxedis G Guerrero Nuevo (La Loma));"));
        this.colonias.add(new Colonia(481, "Predio Canoas"));
        this.colonias.add(new Colonia(482, "PRI"));
        this.colonias.add(new Colonia(483, "Primero de Mayo"));
        this.colonias.add(new Colonia(484, "Primer Presidente"));
        this.colonias.add(new Colonia(485, "Privada Alejandrina"));
        this.colonias.add(new Colonia(486, "Privada Alejandro"));
        this.colonias.add(new Colonia(487, "Privada Aserradero"));
        this.colonias.add(new Colonia(488, "Privada Casuarinas"));
        this.colonias.add(new Colonia(489, "Privada del Sahuaro"));
        this.colonias.add(new Colonia(490, "Privada las Quintas"));
        this.colonias.add(new Colonia(491, "Privada los Sauces"));
        this.colonias.add(new Colonia(492, "Privada Luna"));
        this.colonias.add(new Colonia(493, "Privada Paraíso"));
        this.colonias.add(new Colonia(494, "Privada Perseo 98"));
        this.colonias.add(new Colonia(495, "Privada San Ángel Inn"));
        this.colonias.add(new Colonia(496, "Privada San Lorenzo"));
        this.colonias.add(new Colonia(497, "Privadas del Sahuatoba"));
        this.colonias.add(new Colonia(498, "Privadas San Ignacio"));
        this.colonias.add(new Colonia(499, "Privada Villa Jardín"));
        this.colonias.add(new Colonia(500, "Promotores Sociales"));
        this.colonias.add(new Colonia(501, "Providencia I"));
        this.colonias.add(new Colonia(502, "Providencia II FOVISSSTE"));
        this.colonias.add(new Colonia(503, "Provincial"));
        this.colonias.add(new Colonia(504, "Puerta de La Cantera"));
        this.colonias.add(new Colonia(505, "Puerta del Sol"));
        this.colonias.add(new Colonia(506, "Puerta de San Ignacio"));
        this.colonias.add(new Colonia(507, "Puertas del Sol II"));
        this.colonias.add(new Colonia(508, "Puertas del Sol III"));
        this.colonias.add(new Colonia(509, "Quinta del Real"));
        this.colonias.add(new Colonia(510, "Ranchito la Piedra"));
        this.colonias.add(new Colonia(511, "Rancho Agua Zarca"));
        this.colonias.add(new Colonia(512, "Rancho Alaska 1"));
        this.colonias.add(new Colonia(513, "Rancho Belleza (José Irigoyen));"));
        this.colonias.add(new Colonia(514, "Rancho Cachorros"));
        this.colonias.add(new Colonia(515, "Rancho California"));
        this.colonias.add(new Colonia(516, "Rancho Chapultepec"));
        this.colonias.add(new Colonia(517, "Rancho Corral de Piedra (Postes Negros));"));
        this.colonias.add(new Colonia(518, "Rancho Dalila"));
        this.colonias.add(new Colonia(519, "Rancho de La Cruz"));
        this.colonias.add(new Colonia(520, "Rancho Dos Hermanos"));
        this.colonias.add(new Colonia(521, "Rancho el Apuro"));
        this.colonias.add(new Colonia(522, "Rancho el Arco Iris"));
        this.colonias.add(new Colonia(523, "Rancho el Asturiano"));
        this.colonias.add(new Colonia(524, "Rancho el Canelo"));
        this.colonias.add(new Colonia(525, "Rancho el Consuelo"));
        this.colonias.add(new Colonia(526, "Rancho el Durazno"));
        this.colonias.add(new Colonia(527, "Rancho el Escalón"));
        this.colonias.add(new Colonia(528, "Rancho el Fresno"));
        this.colonias.add(new Colonia(529, "Rancho el Giro"));
        this.colonias.add(new Colonia(530, "Rancho el Maguey"));
        this.colonias.add(new Colonia(531, "Rancho el Manzano"));
        this.colonias.add(new Colonia(532, "Rancho el Mezquite"));
        this.colonias.add(new Colonia(533, "Rancho el Monte"));
        this.colonias.add(new Colonia(534, "Rancho el Norteño"));
        this.colonias.add(new Colonia(535, "Rancho el Paisa"));
        this.colonias.add(new Colonia(536, "Rancho el Paraíso"));
        this.colonias.add(new Colonia(537, "Rancho el Paraíso"));
        this.colonias.add(new Colonia(538, "Rancho el Pilón"));
        this.colonias.add(new Colonia(539, "Rancho el Potrero (Los Parra));"));
        this.colonias.add(new Colonia(540, "Rancho el Sáuz"));
        this.colonias.add(new Colonia(541, "Rancho el Tecolote"));
        this.colonias.add(new Colonia(542, "Rancho el Vegel (Quenay));"));
        this.colonias.add(new Colonia(543, "Rancho Esperanza"));
        this.colonias.add(new Colonia(544, "Rancho Espino"));
        this.colonias.add(new Colonia(545, "Rancho Gas Plus"));
        this.colonias.add(new Colonia(546, "Rancho Hidalgo"));
        this.colonias.add(new Colonia(547, "Rancho Huichapa"));
        this.colonias.add(new Colonia(548, "Rancho Jacarandas"));
        this.colonias.add(new Colonia(549, "Rancho la Abundancia (El Venado));"));
        this.colonias.add(new Colonia(550, "Rancho la Cruz de Orozco"));
        this.colonias.add(new Colonia(551, "Rancho la Galera"));
        this.colonias.add(new Colonia(552, "Rancho Laguna Colorada de Los López"));
        this.colonias.add(new Colonia(553, "Rancho la Joya"));
        this.colonias.add(new Colonia(554, "Rancho la Laguna"));
        this.colonias.add(new Colonia(555, "Rancho la Luna"));
        this.colonias.add(new Colonia(556, "Rancho la Nogalera"));
        this.colonias.add(new Colonia(557, "Rancho la Noria"));
        this.colonias.add(new Colonia(558, "Rancho la Parcela"));
        this.colonias.add(new Colonia(559, "Rancho la Presa de Navacoyán"));
        this.colonias.add(new Colonia(560, "Rancho las Águilas"));
        this.colonias.add(new Colonia(561, "Rancho las Flores"));
        this.colonias.add(new Colonia(562, "Rancho las Nubes"));
        this.colonias.add(new Colonia(563, "Rancho las Nubes"));
        this.colonias.add(new Colonia(564, "Rancho la Soledad (El Capi));"));
        this.colonias.add(new Colonia(565, "Rancho las Potrancas"));
        this.colonias.add(new Colonia(566, "Rancho las Sanjuaneras"));
        this.colonias.add(new Colonia(567, "Rancho la Trnidad"));
        this.colonias.add(new Colonia(568, "Rancho la Vibora"));
        this.colonias.add(new Colonia(569, "Rancho Lorena"));
        this.colonias.add(new Colonia(570, "Rancho los Ángeles"));
        this.colonias.add(new Colonia(571, "Rancho los Arcos del Vergel"));
        this.colonias.add(new Colonia(572, "Rancho los Colorines"));
        this.colonias.add(new Colonia(573, "Rancho los Corrales"));
        this.colonias.add(new Colonia(574, "Rancho los Cuevas"));
        this.colonias.add(new Colonia(575, "Rancho los Duraznos"));
        this.colonias.add(new Colonia(576, "Rancho los Membrillos"));
        this.colonias.add(new Colonia(577, "Rancho los Pelícanos"));
        this.colonias.add(new Colonia(578, "Rancho los Pinos"));
        this.colonias.add(new Colonia(579, "Rancho los Pinos"));
        this.colonias.add(new Colonia(580, "Rancho los Portales Cabalgantes"));
        this.colonias.add(new Colonia(581, "Rancho los Rosales"));
        this.colonias.add(new Colonia(582, "Rancho los Torres"));
        this.colonias.add(new Colonia(583, "Rancho Macías"));
        this.colonias.add(new Colonia(584, "Rancho Madrid"));
        this.colonias.add(new Colonia(585, "Rancho Manuel Cadena"));
        this.colonias.add(new Colonia(586, "Rancho María Esther"));
        this.colonias.add(new Colonia(587, "Rancho Montserrat"));
        this.colonias.add(new Colonia(588, "Rancho Nativitas"));
        this.colonias.add(new Colonia(589, "Rancho Nuevo Monterrey"));
        this.colonias.add(new Colonia(590, "Rancho Ramírez (Sagrado Corazón));"));
        this.colonias.add(new Colonia(591, "Rancho Ramos Vázquez"));
        this.colonias.add(new Colonia(592, "Rancho Revueltas"));
        this.colonias.add(new Colonia(593, "Rancho San Carlos"));
        this.colonias.add(new Colonia(594, "Rancho San Francisco"));
        this.colonias.add(new Colonia(595, "Rancho San Francisco de Calleros"));
        this.colonias.add(new Colonia(596, "Rancho San Martín"));
        this.colonias.add(new Colonia(597, "Rancho San Pedro (San Juan));"));
        this.colonias.add(new Colonia(598, "Rancho Santa Anita"));
        this.colonias.add(new Colonia(599, "Rancho Santa Lucía"));
        this.colonias.add(new Colonia(600, "Rancho Santo Niño"));
        this.colonias.add(new Colonia(601, "Rancho San Vicente"));
        this.colonias.add(new Colonia(602, "Rancho San Zenaido"));
        this.colonias.add(new Colonia(603, "Rancho Tarahumara (Las Fresas));"));
        this.colonias.add(new Colonia(604, "Rancho Tierra Limpia"));
        this.colonias.add(new Colonia(605, "Rancho Tinajas"));
        this.colonias.add(new Colonia(606, "Rancho Viborillas"));
        this.colonias.add(new Colonia(607, "Rancho Viborillas"));
        this.colonias.add(new Colonia(608, "Real del Country"));
        this.colonias.add(new Colonia(609, "Real del Mezquital"));
        this.colonias.add(new Colonia(610, "Real del Naranjal"));
        this.colonias.add(new Colonia(611, "Real del Prado"));
        this.colonias.add(new Colonia(612, "Real de Villas"));
        this.colonias.add(new Colonia(613, "Real Victoria I"));
        this.colonias.add(new Colonia(614, "Real Victoria II"));
        this.colonias.add(new Colonia(615, "Recuerdos del Pasado"));
        this.colonias.add(new Colonia(616, "Reforma"));
        this.colonias.add(new Colonia(617, "Regocijo"));
        this.colonias.add(new Colonia(618, "Residencial Caletto"));
        this.colonias.add(new Colonia(619, "Residencial Casa Blanca"));
        this.colonias.add(new Colonia(620, "Residencial del Valle"));
        this.colonias.add(new Colonia(621, "Residencial Hortencia"));
        this.colonias.add(new Colonia(622, "Residencial las Alamedas"));
        this.colonias.add(new Colonia(623, "Residencial La Salle"));
        this.colonias.add(new Colonia(624, "Residencial las Palmas"));
        this.colonias.add(new Colonia(625, "Residencial los Laureles"));
        this.colonias.add(new Colonia(626, "Residencial Plaza Alejandra"));
        this.colonias.add(new Colonia(627, "Residencial Puerta de Hierro"));
        this.colonias.add(new Colonia(628, "Residencial Santa Teresa"));
        this.colonias.add(new Colonia(629, "Residencial Villa Dorada"));
        this.colonias.add(new Colonia(630, "Residencia Santa Clara"));
        this.colonias.add(new Colonia(631, "Ricardo Flores Magón"));
        this.colonias.add(new Colonia(632, "Ricardo Rosales (SCT));"));
        this.colonias.add(new Colonia(633, "Riconada San Javier"));
        this.colonias.add(new Colonia(634, "Rinconada Badiola"));
        this.colonias.add(new Colonia(635, "Rinconada Bugambilias"));
        this.colonias.add(new Colonia(636, "Rinconada del Paraíso"));
        this.colonias.add(new Colonia(637, "Rinconada las Flores"));
        this.colonias.add(new Colonia(638, "Rinconada San Antonio"));
        this.colonias.add(new Colonia(639, "Rinconada Sol"));
        this.colonias.add(new Colonia(640, "Rincón de Agricultura"));
        this.colonias.add(new Colonia(641, "Rincón del Lobo"));
        this.colonias.add(new Colonia(642, "Río Dorado"));
        this.colonias.add(new Colonia(643, "Río Verde"));
        this.colonias.add(new Colonia(644, "Rodriguez Puebla"));
        this.colonias.add(new Colonia(645, "Roma"));
        this.colonias.add(new Colonia(646, "Roma"));
        this.colonias.add(new Colonia(647, "Rosas del Tepeyac"));
        this.colonias.add(new Colonia(648, "SAHOP"));
        this.colonias.add(new Colonia(649, "San Ángel"));
        this.colonias.add(new Colonia(650, "San Benito"));
        this.colonias.add(new Colonia(651, "San Carlo"));
        this.colonias.add(new Colonia(652, "San Carlos"));
        this.colonias.add(new Colonia(653, "San Carlos"));
        this.colonias.add(new Colonia(654, "San Diego"));
        this.colonias.add(new Colonia(655, "San Fernando"));
        this.colonias.add(new Colonia(656, "San Francisco del Manzanal"));
        this.colonias.add(new Colonia(657, "San Gabriel"));
        this.colonias.add(new Colonia(658, "San Ignacio"));
        this.colonias.add(new Colonia(659, "San Ignacio de Loyola"));
        this.colonias.add(new Colonia(660, "San Isidro"));
        this.colonias.add(new Colonia(661, "San Isidro"));
        this.colonias.add(new Colonia(662, "San Jorge"));
        this.colonias.add(new Colonia(663, "San José"));
        this.colonias.add(new Colonia(664, "San José"));
        this.colonias.add(new Colonia(665, "San José de Animas"));
        this.colonias.add(new Colonia(666, "San José de La Vinata"));
        this.colonias.add(new Colonia(667, "San José del Molino"));
        this.colonias.add(new Colonia(668, "San José II"));
        this.colonias.add(new Colonia(669, "San Juan"));
        this.colonias.add(new Colonia(670, "San Luis"));
        this.colonias.add(new Colonia(671, "San Luis"));
        this.colonias.add(new Colonia(672, "San Marcos"));
        this.colonias.add(new Colonia(673, "San Martín de Porres"));
        this.colonias.add(new Colonia(674, "San Mateo"));
        this.colonias.add(new Colonia(675, "San Miguel"));
        this.colonias.add(new Colonia(676, "San Miguel"));
        this.colonias.add(new Colonia(677, "San Miguel"));
        this.colonias.add(new Colonia(678, "San Pedro de La Maquina"));
        this.colonias.add(new Colonia(679, "San Roque"));
        this.colonias.add(new Colonia(680, "Santa Amelia"));
        this.colonias.add(new Colonia(681, "Santa Anita"));
        this.colonias.add(new Colonia(682, "Santa Cruz"));
        this.colonias.add(new Colonia(683, "Santa Cruz del Río"));
        this.colonias.add(new Colonia(684, "Santa Cruz de San Javier"));
        this.colonias.add(new Colonia(685, "Santa Fe"));
        this.colonias.add(new Colonia(686, "Santa María"));
        this.colonias.add(new Colonia(687, "Santa Teresa"));
        this.colonias.add(new Colonia(688, "Santiago Bayacora"));
        this.colonias.add(new Colonia(689, "San Vicente de Chupaderos"));
        this.colonias.add(new Colonia(690, "Sarh"));
        this.colonias.add(new Colonia(691, "Sebastián Lerdo de Tejada"));
        this.colonias.add(new Colonia(692, "SEDUE"));
        this.colonias.add(new Colonia(693, "Senderos"));
        this.colonias.add(new Colonia(694, "Sergio Méndez Arceo"));
        this.colonias.add(new Colonia(695, "Silvestre Dorador"));
        this.colonias.add(new Colonia(696, "Silvestre Revueltas"));
        this.colonias.add(new Colonia(697, "Solidaridad"));
        this.colonias.add(new Colonia(698, "Tenochtitlan"));
        this.colonias.add(new Colonia(699, "Terrenos del Ferrocarril"));
        this.colonias.add(new Colonia(700, "Tierra y Libertad"));
        this.colonias.add(new Colonia(701, "Toledo"));
        this.colonias.add(new Colonia(702, "Tomás Urbina"));
        this.colonias.add(new Colonia(703, "Tres Misiones"));
        this.colonias.add(new Colonia(704, "Une"));
        this.colonias.add(new Colonia(705, "Unidad Guadalupe"));
        this.colonias.add(new Colonia(706, "Unidad Habitacional Labor de Guadalupe"));
        this.colonias.add(new Colonia(707, "Unidos Venceremos"));
        this.colonias.add(new Colonia(708, "Unión de Rodriguez"));
        this.colonias.add(new Colonia(709, "Universal"));
        this.colonias.add(new Colonia(710, "Valentín Gómez Farias"));
        this.colonias.add(new Colonia(711, "Valle Alegre"));
        this.colonias.add(new Colonia(712, "Valle de Cristo"));
        this.colonias.add(new Colonia(713, "Valle de Guadalupe I"));
        this.colonias.add(new Colonia(714, "Valle de Guadalupe II"));
        this.colonias.add(new Colonia(715, "Valle del Guadiana"));
        this.colonias.add(new Colonia(716, "Valle del Mezquital I"));
        this.colonias.add(new Colonia(717, "Valle del Paseo"));
        this.colonias.add(new Colonia(718, "Valle del Sur"));
        this.colonias.add(new Colonia(719, "Valle de México"));
        this.colonias.add(new Colonia(720, "Valle Florido"));
        this.colonias.add(new Colonia(721, "Valle Oriente"));
        this.colonias.add(new Colonia(722, "Vallesol"));
        this.colonias.add(new Colonia(723, "Valle Verde Oriente"));
        this.colonias.add(new Colonia(724, "Valle Verde Sur"));
        this.colonias.add(new Colonia(725, "Venecia"));
        this.colonias.add(new Colonia(726, "Vergel del Desierto"));
        this.colonias.add(new Colonia(727, "Versalles"));
        this.colonias.add(new Colonia(728, "Veteranos de La Revolución"));
        this.colonias.add(new Colonia(729, "Vicente Guerrero"));
        this.colonias.add(new Colonia(730, "Vicente Suárez"));
        this.colonias.add(new Colonia(731, "Victoria de Durango"));
        this.colonias.add(new Colonia(732, "Victoria de Durango Centro"));
        this.colonias.add(new Colonia(733, "Villa Alegre"));
        this.colonias.add(new Colonia(734, "Villa Antigua"));
        this.colonias.add(new Colonia(735, "Villa Blanca"));
        this.colonias.add(new Colonia(736, "Villa de Guadalupe"));
        this.colonias.add(new Colonia(737, "Villa Jacarandas"));
        this.colonias.add(new Colonia(738, "Villa los Remedios"));
        this.colonias.add(new Colonia(739, "Villa Montemorelos"));
        this.colonias.add(new Colonia(740, "Villas Alpinas"));
        this.colonias.add(new Colonia(741, "Villas Americanas"));
        this.colonias.add(new Colonia(742, "Villas Campestre"));
        this.colonias.add(new Colonia(743, "Villas de Guadiana VI"));
        this.colonias.add(new Colonia(744, "Villas de Guadiana VII"));
        this.colonias.add(new Colonia(745, "Villas del Carmen"));
        this.colonias.add(new Colonia(746, "Villas del Edén"));
        this.colonias.add(new Colonia(747, "Villas del Guadiana I"));
        this.colonias.add(new Colonia(748, "Villas del Guadiana II"));
        this.colonias.add(new Colonia(749, "Villas del Guadiana III"));
        this.colonias.add(new Colonia(750, "Villas del Guadiana IV"));
        this.colonias.add(new Colonia(751, "Villas del Guadiana V (Mixto));"));
        this.colonias.add(new Colonia(752, "Villas del Manantial (Ameyal));"));
        this.colonias.add(new Colonia(753, "Villas del Pedregal I"));
        this.colonias.add(new Colonia(754, "Villas del Pedregal II"));
        this.colonias.add(new Colonia(755, "Villas del Sol"));
        this.colonias.add(new Colonia(756, "Villas de San Francisco"));
        this.colonias.add(new Colonia(757, "Villas Doradas"));
        this.colonias.add(new Colonia(758, "Villas Doradas II"));
        this.colonias.add(new Colonia(759, "Villas Santa Teresa"));
        this.colonias.add(new Colonia(760, "Villa Universitaria"));
        this.colonias.add(new Colonia(761, "Viñedos"));
        this.colonias.add(new Colonia(762, "Vista Hermosa del Guadiana"));
        this.colonias.add(new Colonia(763, "Vivah El Alacrán"));
        this.colonias.add(new Colonia(764, "Vivah Reforma I"));
        this.colonias.add(new Colonia(765, "Vivah Reforma II"));

    }

    public List<Colonia> searchColonia(String text) {

        List<Colonia> result = new ArrayList<Colonia>();
        int index = 0;
        while (result.size() <= 5 && index < colonias.size()) {
            Colonia c = colonias.get(index++);
            if (c.getNombre().toLowerCase().contains(text.toLowerCase())) {
                result.add(c);
            }
        }

        return result;
    }

}
